spring:
  application:
    name: expense-management-server
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: mongodb://admin:password@localhost:27017/expense-management?authSource=admin

security:
  jwt:
    secret: dGVzdC1qd3Qtc2VjcmV0LXRlc3Qtand0LXNlY3JldC10ZXN0LWp3dC1zZWNyZXQtdGVzdC1qd3Qtc2VjcmV0LXRlc3Qtand0LXNlY3JldA==
    expiration: 3600
