spring:
  application:
    name: expense-management-server
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_TOKEN_EXPIRATION_IN_SECONDS}
