name: cd

# The workflow runs when a push was made to master branch (PR was merged to master)
on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar -x test

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: expense-management-server
          path: build/libs/*.jar
          retention-days: 2
